name: Feature Request
description: Suggest a new feature or enhancement for Fluxel
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your idea.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: In one or two sentences, describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe how you envision this feature working...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative approaches you've thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of Fluxel does this feature relate to?
      options:
        - Editor - Code editing features
        - Visual Editor - Visual/preview editing
        - Workbench - UI/UX and layout
        - File Management - File operations and workspace
        - Build System - Building and compilation
        - Git/Version Control - Git integration
        - Settings/Preferences - Configuration options
        - Language Support - Programming language features
        - Performance - Speed and optimization
        - Accessibility - Accessibility improvements
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my workflow
        - High - Would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. As a developer, I would use this to...
        2. When working on..., this would help me...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots from other tools, or visual examples
      placeholder: Drag and drop images or provide links to similar features in other applications

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical considerations or implementation ideas?
      placeholder: This could potentially be implemented using...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you interested in implementing this feature?
      options:
        - label: I am willing to submit a PR to implement this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would help us understand your request
      placeholder: Any additional context, references, or background...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with Fluxel's goals as an IDE application
          required: true
        - label: I have provided sufficient detail for the feature to be understood
          required: true
