/**
 * Fluxel Performance Profiling Types
 * 
 * TypeScript types for the profiling API exposed by the Rust backend.
 * These types mirror the Rust structs in src-tauri/src/profiling/.
 */

// =============================================================================
// Span Categories
// =============================================================================

/**
 * Category of a span for attribution grouping.
 */
export type SpanCategory =
    | 'tauri_command'
    | 'file_io'
    | 'git_operation'
    | 'lsp_request'
    | 'search'
    | 'workspace'
    | 'build_operation'
    | 'diagnostics'
    | 'frontend_render'
    | 'frontend_interaction'
    | 'frontend_network'
    | 'backend_operation'
    | 'other';

/**
 * Frontend-specific span categories.
 */
export type FrontendCategory =
    | 'frontend_render'
    | 'frontend_interaction'
    | 'frontend_network';

// =============================================================================
// Span Types
// =============================================================================

/**
 * Summary of a completed span.
 */
export interface SpanSummary {
    /** Unique identifier for this span */
    id: string;
    /** Parent span ID, if any */
    parentId: string | null;
    /** Span name (usually function name) */
    name: string;
    /** Tracing target (usually module path) */
    target: string;
    /** Inferred category for grouping */
    category: SpanCategory;
    /** Relative start time in milliseconds */
    startTimeMs: number;
    /** Duration in milliseconds */
    durationMs: number;
    /** Captured fields as key-value pairs */
    fields: [string, string][];
}

/**
 * Input for recording a frontend span.
 */
export interface FrontendSpanInput {
    /** Unique span ID generated by the frontend */
    id: string;
    /** Span name (e.g., "MyComponent:render") */
    name: string;
    /** Category of the span */
    category: FrontendCategory | SpanCategory;
    /** Duration in milliseconds */
    durationMs: number;
    /** Optional parent span ID */
    parentId?: string;
    /** Optional metadata as key-value pairs */
    metadata?: [string, string][];
}

// =============================================================================
// Status & Reports
// =============================================================================

/**
 * Profiler status information.
 */
export interface ProfilerStatus {
    /** Whether profiling is enabled */
    enabled: boolean;
    /** Number of spans currently stored */
    spanCount: number;
    /** Maximum buffer capacity */
    bufferCapacity: number;
    /** Active session ID, if any */
    activeSessionId: string | null;
}

/**
 * Breakdown of time spent in a specific category.
 */
export interface CategoryBreakdown {
    /** The category */
    category: SpanCategory;
    /** Total wall-clock time in this category */
    totalTimeMs: number;
    /** Self time (excluding time in child spans) */
    selfTimeMs: number;
    /** Percentage of total operation time */
    percentage: number;
    /** Number of spans in this category */
    spanCount: number;
}

/**
 * Hierarchical span node for tree analysis.
 */
export interface SpanTreeNode {
    /** The span data */
    span: SpanSummary;
    /** Self time (excluding children) */
    selfTimeMs: number;
    /** Direct children of this span */
    children: SpanTreeNode[];
    /** Depth in the tree (0 = root) */
    depth: number;
}

/**
 * Complete attribution report for an operation.
 */
export interface AttributionReport {
    /** The root span of the operation */
    rootSpan: SpanSummary;
    /** Total wall-clock time for the operation */
    totalTimeMs: number;
    /** Breakdown by category */
    breakdowns: CategoryBreakdown[];
    /** Critical path - spans that determined total time */
    criticalPath: SpanSummary[];
    /** Top spans by self-time (hotspots) */
    hotspots: SpanSummary[];
    /** Hierarchical tree structure for flame graph visualization */
    tree: SpanTreeNode | null;
}

// =============================================================================
// Session Types
// =============================================================================

/**
 * A profiling session that groups spans for analysis.
 */
export interface ProfilingSession {
    /** Unique session identifier */
    id: string;
    /** Human-readable session name */
    name: string;
    /** Session start time in milliseconds (from profiler reference time) */
    startTimeMs: number;
    /** Session end time in milliseconds (null if still active) */
    endTimeMs: number | null;
    /** Number of spans captured in this session */
    spanCount: number;
}

/**
 * Category breakdown within a session.
 */
export interface CategorySessionBreakdown {
    category: SpanCategory;
    totalTimeMs: number;
    spanCount: number;
    percentage: number;
}

/**
 * Summary report when a session ends.
 */
export interface SessionReport {
    /** The session details */
    session: ProfilingSession;
    /** Time breakdown by category */
    breakdowns: CategorySessionBreakdown[];
    /** Top spans by duration */
    topSpans: SpanSummary[];
    /** Total duration of all spans (may exceed session duration due to overlap) */
    totalSpanTimeMs: number;
}

// =============================================================================
// Export Types
// =============================================================================

/**
 * Export format for profiling data.
 */
export type ExportFormat = 'json' | 'chrome_trace';

// =============================================================================
// API Interface
// =============================================================================

/**
 * Profiler API functions.
 * 
 * These map to the Tauri commands in src-tauri/src/profiling/commands.rs
 */
export interface ProfilerApi {
    // Basic commands
    /** Enable or disable profiling */
    setEnabled: (enabled: boolean) => Promise<void>;
    /** Get current profiler status */
    getStatus: () => Promise<ProfilerStatus>;
    /** Get recent spans */
    getRecentSpans: (limit?: number) => Promise<SpanSummary[]>;
    /** Get attribution report for a span tree */
    getAttribution: (rootSpanId: string) => Promise<AttributionReport>;
    /** Clear all stored spans */
    clear: () => Promise<void>;

    // Session commands
    /** Start a named profiling session */
    startSession: (name: string) => Promise<string>;
    /** End a session and get the report */
    endSession: (sessionId: string) => Promise<SessionReport>;

    // Frontend span recording
    /** Record a span from the frontend */
    recordFrontendSpan: (span: FrontendSpanInput) => Promise<void>;

    // Export
    /** Export spans in the specified format */
    export: (format: ExportFormat, sessionName?: string, limit?: number) => Promise<string>;
}

